# Generated by Django 3.1.7 on 2021-03-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=100)),
                ('numero_asiento', models.CharField(max_length=4)),
                ('puerta_de_salida', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending')], max_length=15)),
                ('salida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='travels.salida')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='travels.user')),
            ],
        ),
    ]
